### ISSUE TITLE
null pointer when rule contains .send

### ISSUE THREAD

**Issue by shortwavedave** [jason-lang/jason#10]
asl rule is as follows:

`uavStatus(U) :- .send(uavMgr,askOne,managedUavs(X),U).`

from repl agent I make the request:

`.send(agent,askOne,uavStatus(U)).`

The console shows a null pointer exception:

> [InternalActionLiteral] Error in internal action '.send(uavMgr,askOne,managedUavs(X),U)' (/home/david/src/workspace/agentCreator/src/asl/breccia.asl:5): null
java.lang.NullPointerException
	at jason.asSemantics.Circumstance.addPendingIntention(Circumstance.java:405)
	at jason.stdlib.send.execute(send.java:142)
	at jason.asSyntax.InternalActionLiteral.logicalConsequence(InternalActionLiteral.java:101)
	at jason.asSyntax.Literal$1.get(Literal.java:495)
	at jason.asSyntax.Literal$1.hasNext(Literal.java:382)
	at jason.asSemantics.TransitionSystem.applyFindOp(TransitionSystem.java:526)
	at jason.asSemantics.TransitionSystem.applySemanticRuleDeliberate(TransitionSystem.java:217)
	at jason.asSemantics.TransitionSystem.deliberate(TransitionSystem.java:1488)
	at jason.infra.centralised.CentralisedAgArch.deliberate(CentralisedAgArch.java:187)
	at jason.infra.centralised.CentralisedAgArch.reasoningCycle(CentralisedAgArch.java:211)
	at jason.infra.centralised.CentralisedAgArch.run(CentralisedAgArch.java:231)
	at java.lang.Thread.run(Thread.java:748)

I'm still learning the language, but it seems odd to get an exception like that. Looking at the execute function in send, the null pointer is getting passed on line 142:

` lastSendWasSynAsk = m.isAsk() && args.length > 3;
        if (lastSendWasSynAsk) {
            m.setSyncAskMsgId();
            ts.getC().addPendingIntention(m.getMsgId(), ts.getC().getSelectedIntention());
        }`

the "ts.getC().getSelectedIntention"

Any idea why that might return a null? Is it appropriate to .send in a rule?

**Comment by jomifred** [comment]
Hi, the message error is indeed a bit strange and we will improve that. However, .send cannot be used in rules (or plan context) because it is a kind of "external" action ... something goes outside the agent with this action. It can even suspend the some intention when the performative ask is used. 
Rule are used for internal reasoning and can not change the environment.... 

In Jason we clearly separate what is theoretical reasoning (in rules) and what is practical reasoning (in plans' bod). While the output of the former is beliefs, the output of the second is actions. Since .send is an action, it can be the output of practical reasoning only.

best,

Jomi
